server:
  port: 8080
  contextPath: /routeplanner/api/v1

spring:
  application:
    name: RoutePlanner

routePlanner:
  limitRecordsPerPage: 50
  minimumDifferenceInHoursBetweenArrivalAndNextDeparture: 2