package es.demo.routeplanner.model;

public enum ErrorType {

    // Generic Errors
    BAD_REQUEST_ERROR
    , RESOURCE_NOT_FOUND_ERROR
    , INTERNAL_SERVER_ERROR
    , NOT_SUPPORTED_ERROR

    // Custom Errors
    , DEPARTURE_TIME_INVALID_FORMAT
    , ARRIVAL_TIME_INVALID_FORMAT
    , DEPARTURE_TIME_UTC_AFTER_ARRIVAL_TIME_UTC
    , DEPARTURE_NOT_IATA_CODE
    , ARRIVAL_NOT_IATA_CODE


}